config/routes.rb
Rails.application.routes.draw do
  devise_for :ranters

  root 'home#index'

  resources :rants, only: [:create]
  resources :ranters, only: [:index, :show] do
    member do
      get 'follow'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'Ranter'
  belongs_to :followee, class_name: 'Ranter'
end

app/models/rant.rb
class Rant < ApplicationRecord
  belongs_to :ranter

  scope :descending, -> { order("created_at DESC") }

  mount_uploader :photo, PhotoUploader
end

app/models/ranter.rb
require 'digest/md5'

class Ranter < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rants

  has_many :follows_as_followee, class_name: 'Follow', foreign_key: :followee_id
  has_many :follows_as_follower, class_name: 'Follow', foreign_key: :follower_id

  has_many :followers, through: :follows_as_followee
  has_many :followees, through: :follows_as_follower

  def gravatar_url
    hash = Digest::MD5.hexdigest(email.downcase)
    image_src = "https://www.gravatar.com/avatar/#{hash}"
  end

  def follow!(followee)
    self.followees << followee
  end

  def followable?(follower)
    follower != self && !self.followers.include?(follower)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:handle])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :ensure_current_user, only: [:index]

  def index
    @ranter = current_ranter
  end

  private

  def ensure_current_user
    redirect_to new_ranter_session_path unless current_ranter
  end
end

app/controllers/ranters_controller.rb
class RantersController < ApplicationController
  def index
    @ranters = Ranter.all
  end

  def follow
    followee = Ranter.find_by(id: params[:id])
    follower = current_ranter

    follower.follow!(followee)

    redirect_to root_path
  end
end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
  def create
    current_ranter.rants.create rant_params

    redirect_to root_path
  end

  private

  def rant_params
    params.require(:rant).permit(:message, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_controller_helper.rb
module HomeControllerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ranters_helper.rb
module RantersHelper
end

app/helpers/rants_helper.rb
module RantsHelper
end

app/views/home/index.html.erb
<h2><%= @ranter.handle %></h2>
<img src="<%= @ranter.gravatar_url %>" />

<%= link_to 'Ranters', ranters_path %>
<%= link_to 'Signout', destroy_ranter_session_path, method: :delete %>

<%= form_for Rant.new  do |f| %>
  <%= f.text_field :message %>
  <%= f.file_field :photo %>
  <%= f.submit 'Rant' %>
<% end %>

<ul>
  <% @ranter.rants.descending.each do |rant| %>
    <li>
      <p><%= rant.message %></p>
      <span><%= rant.created_at %></span>
      <a href="<%= rant.photo.url %>">
        <img src="<%= rant.photo.url(:thumbnail) %>">
      </a>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rants</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ranters/index.html.erb
<ul>
  <% @ranters.each do |ranter| %>
    <li>
      <%= link_to ranter.handle, ranter %>
      <% if ranter.followable?(current_ranter) %>
        <%= link_to 'Follow', follow_ranter_path(ranter) %>
      <% end %>
    </li>
  <% end %>
</ul>